// src/core/refinery/taxonomy/types/taxonomy.ts

/** A node in the taxonomy tree — represents a folder. */
export interface TaxonomyNode {
  /** Folder name (sanitized, single segment). */
  name: string;
  /** Human-readable description of what this folder contains. */
  description: string;
  /** Child folders. */
  children: TaxonomyNode[];
  /** Chunk hashes assigned to this folder (terminal assignment). */
  assignedChunks: string[];
}

/**
 * Proposed taxonomy — the ideal folder tree for new chunks,
 * generated by LLM without considering existing output structure.
 */
export interface ProposedTaxonomy {
  /** Root nodes of the proposed folder tree. */
  roots: TaxonomyNode[];
  /** Brief rationale from the LLM. */
  rationale: string;
}
