//! # Query Preprocessing
//!
//! Transforms the raw user query into a set of weighted [`QueryVariant`]s.
//! Each stage optionally adds or replaces variants:
//!
//! 1. **Original** — the user's query as-is.
//! 2. **Translated** — the query translated into the vault's dominant language.
//! 3. **HyDE** — a synthetic answer document generated by the LLM for embedding.
//! 4. **Synonyms** — dictionary or LLM-expanded alternative phrasings.

pub mod variants;
pub mod translate;
pub mod hyde;
pub mod synonyms;

pub use variants::{build_variants, dedup_variants, default_synonyms};
pub use translate::maybe_translate_query;
pub use hyde::run_hyde;
pub use synonyms::{expand_static, expand_llm};
