//! # Query Variant Types
//!
//! Internal types used to represent preprocessed query variants during pipeline execution.
//! These types are not exposed over the Tauri IPC boundary.

/// Indicates how a `QueryVariant` was produced during preprocessing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VariantSource {
    /// The user's original query text.
    Original,
    /// A translation of the original query into the vault language.
    Translated,
    /// A synthetic document generated by HyDE to capture semantic context.
    Hyde,
    /// A term-level synonym of one of the other variants.
    Synonym,
}

/// One candidate query to be embedded and searched.
#[derive(Debug, Clone)]
pub struct QueryVariant {
    /// Actual query text to embed and/or search.
    pub text: String,
    /// ISO-639-1 language tag of `text`.
    pub lang: String,
    /// How this variant was produced (for logging/debugging).
    pub source: VariantSource,
    /// Fusion weight in the final RRF merge across variants.
    pub weight: f32,
    /// If `true`, this variant is skipped in FTS5/keyword search
    /// and only used for vector similarity (e.g. HyDE hypothetical documents).
    pub vector_only: bool,
}
