// src/core/refinery/constants.ts

export const REFINERY_CONSTANTS = {
  /** Cosine similarity above which chunks are merged into an existing file. */
  MERGE_SIMILARITY_THRESHOLD: 0.85,
  /** Cosine similarity above which chunks are treated as near-duplicates and rejected. */
  NEAR_DUP_THRESHOLD: 0.98,
  /** Number of similar chunks to fetch from output vault for dedup comparison. */
  DEDUP_TOP_K: 5,
  /** Maximum number of chunks to send to LLM in a single taxonomy call. */
  MAX_CHUNKS_PER_TAXONOMY_CALL: 50,
  /** Maximum number of chunks per placement call (smaller because placement is more complex). */
  MAX_CHUNKS_PER_PLACEMENT_CALL: 30,
  /** Maximum folder tree depth generated by taxonomy LLM. */
  MAX_DEPTH_OF_GENERATED_TREE: 4,
  /** Minimum chunk text length to consider for LLM-based merge. */
  MIN_CHUNK_LENGTH_FOR_MERGE: 20,
  /** Max characters in a chunk preview sent to LLM (truncate longer). */
  MAX_CHUNK_PREVIEW_CHARS: 500,
  /** Default output root relative to vault root. */
  DEFAULT_OUTPUT_ROOT: "output",
  /** Default inbox root relative to vault root. */
  DEFAULT_INBOX_ROOT: "inbox",
  /** Default dry-run mode — only produce plans, don't write files. */
  DEFAULT_DRY_RUN: true,
} as const;
